name: Build CruelKernel with KernelSU

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        model: [ "N975F" ]  # 👈 CHANGE TO YOUR MODEL

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison build-essential ccache clang flex \
          g++ gcc gcc-aarch64-linux-gnu git gnupg libelf-dev libncurses-dev \
          libssl-dev lld python3 unzip zstd

      - name: Kernel Configure
        run: |
          ./cruelbuild config                    \
                       model=${{ matrix.model }} \
                       name="Cruel-KSU"          \
                       +nohardening              \
                       +wireguard                \
                       +ttl                      \
                       +sdfat                    \
                       +1000hz                   \
                       os_patch_level=2099-12

      - name: Apply KernelSU patch
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Build Kernel
        run: ./cruelbuild mkimg

      - name: Upload boot.img
        uses: actions/upload-artifact@v4    # ✅ FIXED: v3 → v4
        with:
          name: boot-${{ matrix.model }}
          path: boot.img
